describe('template spec', () => {
  it('Edit Account Information Success - Firstname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('yoga')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'yoga pratama') //
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('budi')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
  })

  it('Edit Account Information Success - Lastname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('prakasa')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi prakasa') //
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('pratama')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
  })

  it('Edit Account Information Change Name - Success - Firstname and Lastname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('yoga')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('prakasa')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'yoga prakasa') //
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('budi')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('pratama')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
  })

  it('Edit Account Information Change Name - Failed - Delete Firstname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#firstname-error').should('contain.text', 'This is a required field.')
  })

  it('Edit Account Information Change Name - Success - Delete Lastname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#lastname').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#lastname-error').should('contain.text', 'This is a required field.')
  })

  it('Edit Account Information Change Name - Failed - Delete Firstname and Lastname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#lastname').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#firstname-error').should('contain.text', 'This is a required field.')
    cy.get('#lastname-error').should('contain.text', 'This is a required field.')
  })

  it('Edit Account Information Change Email - Success - Replace Email', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-email').click()
    cy.get('#email').clear()
    cy.get('#email').type('budiadmin1@gmail.com')
    cy.get('#current-password').type('budi12345.,')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Customer Login')
    cy.get('.message-success').should('contain.text', 'You saved the account information.')//
    cy.get('#email').type('budiadmin1@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-email').click()
    cy.get('#email').clear()
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#current-password').type('budi12345.,')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Customer Login')
    cy.get('.message-success').should('contain.text', 'You saved the account information.')//
  })

  it('Edit Account Information Change Email - Failed - Email No Filled', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-email').click()
    cy.get('#email').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#email-error').should('contain.text', 'This is a required field.')
    cy.get('#current-password-error').should('contain.text', 'This is a required field.')
  })

  it('Edit Account Information Change Email - Failed - Email Validation', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-email').click()
    cy.get('#email').clear()
    cy.get('#email').type('budiadmin1')
    cy.get('#current-password').type('budi12345.,')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#email-error').should('contain.text', 'Please enter a valid email address.')
  })

  it('Edit Account Information Change Password - Success - Change Password', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-password').click()
    cy.get('#current-password').type('budi12345.,')
    cy.get('#password').type('admin12345.,')
    cy.get('#password-confirmation').type('admin12345.,')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()//
    cy.get('.base').should('contain.text', 'Customer Login')
    cy.get('.message-success').should('contain.text', 'You saved the account information.')//
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('admin12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-password').click()
    cy.get('#current-password').type('admin12345.,')
    cy.get('#password').type('budi12345.,')
    cy.get('#password-confirmation').type('budi12345.,')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Customer Login')
    cy.get('.message-success').should('contain.text', 'You saved the account information.')//
  })

  it('Edit Account Information Change Password - Failed - Change Password Confirmation', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-password').click()
    cy.get('#current-password').type('budi12345.,')
    cy.get('#password').type('admin12345.,')
    cy.get('#password-confirmation').type('admin12345.')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()//
    cy.get('#password-confirmation-error').should('contain.text', 'Please enter the same value again.')
  })

  it('Edit Account Information Change Password - Failed - Change Password Current', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-password').click()
    cy.get('#current-password').type('budi12345.,')
    cy.get('#password').type('admin')
    cy.get('#password-confirmation').type('admin')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()//
    cy.get('#password-error').should('contain.text', 'Minimum length of this field must be equal or greater than 8 symbols.')
  })

  it('Edit Account Information Change Password - Failed - No Fill Password Field', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#change-password').click()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()//
    cy.get('#current-password-error').should('contain.text', 'This is a required field.')
    cy.get('#password-error').should('contain.text', 'This is a required field.')
    cy.get('#password-confirmation-error').should('contain.text', 'This is a required field.')
  })
})