describe('template spec', () => {
  it('Edit Account Information Success - Firstname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('yoga')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'yoga pratama') //
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('budi')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
  })

  it('Edit Account Information Success - Lastname User', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('prakasa')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi prakasa') //
    cy.get(':nth-child(7) > a').click()
    cy.get('.base').should('contain.text', 'Edit Account Information')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('pratama')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.message-success').should('contain.text', 'You saved the account information.')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
  })
})