describe('template spec', () => {
  // it('Edit Address - Success - Select Country Indonesia', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.get('.panel > .header > .authorization-link > a').click()
  //   cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
  //   cy.get('#email').type('budiadmin@gmail.com')
  //   cy.get('#pass').type('budi12345.,')
  //   cy.get('#send2').click()
  //   cy.get('.base').should('contain.text', 'Home Page')
  //   cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  //   cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  //   cy.get('.base').should('contain.text', 'My Account')
  //   cy.get('.box-content > p').should('contain.text', 'budi pratama')
  //   cy.get('.items > :nth-child(6) > a').click()
  //   cy.get('.base').should('contain.text', 'Add New Address')
  //   cy.get('#country').select('Indonesia')
  //   cy.get('#company').type('Jaya Abadi')
  //   cy.get('#telephone').type('085123678345')
  //   cy.get('#street_1').type('Jalan Lancar')
  //   cy.get('#city').type('Surabaya')
  //   cy.get('#region').type('Jawa Timur')
  //   cy.get('#zip').type('60182')
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
  //   cy.get('.base').should('contain.text', 'Address Book')
  //   cy.get('.message-success').should('contain.text', 'You saved the address.')
  //   cy.get('.box-address-billing > .box-content > address').should('contain.text', '085123678345')
  // })
})