describe('template spec', () => {
  // it('Add Address - Success - Add New Address First Time Select Country Indonesia', () => {
  //   cy.visit('https://magento.softwaretestingboard.com/')
  //   cy.get('.panel > .header > .authorization-link > a').click()
  //   cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
  //   cy.get('#email').type('budiadmin@gmail.com')
  //   cy.get('#pass').type('budi12345.,')
  //   cy.get('#send2').click()
  //   cy.get('.base').should('contain.text', 'Home Page')
  //   cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  //   cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  //   cy.get('.base').should('contain.text', 'My Account')
  //   cy.get('.box-content > p').should('contain.text', 'budi pratama')
  //   cy.get('.items > :nth-child(6) > a').click()
  //   cy.get('.base').should('contain.text', 'Add New Address')
  //   cy.get('#country').select('Indonesia')
  //   cy.get('#company').type('Jaya Abadi')
  //   cy.get('#telephone').type('085123678345')
  //   cy.get('#street_1').type('Jalan Lancar')
  //   cy.get('#city').type('Surabaya')
  //   cy.get('#region').type('Jawa Timur')
  //   cy.get('#zip').type('60182')
  //   cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
  //   cy.get('.base').should('contain.text', 'Address Book')
  //   cy.get('.message-success').should('contain.text', 'You saved the address.')
  // })

  it('Add Address - Success - Add New on Billing Address', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.column > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Add New Address')
    cy.get('#country').select('Indonesia')
    cy.get('#company').type('Lurus Terus')
    cy.get('#telephone').type('085987234675')
    cy.get('#street_1').type('Jalan Lurus')
    cy.get('#city').type('Probolinggo')
    cy.get('#region').type('Jawa Timur')
    cy.get('#zip').type('60890')
    cy.get('#primary_billing').click()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.message-success').should('contain.text', 'You saved the address.')
  })

  it('Add Address - Success - Add New on Shipping Address', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.column > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Add New Address')
    cy.get('#country').select('United States')
    cy.get('#company').type('Origami')
    cy.get('#telephone').type('+16904561238792')
    cy.get('#street_1').type('Ori Street')
    cy.get('#city').type('San diego')
    cy.get('#region_id').select('California')
    cy.get('#zip').type('16098')
    cy.get('#primary_shipping').click()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.message-success').should('contain.text', 'You saved the address.')
  })

  it('Edit Address - Change Billing Address - Success - Change All Field on Billing Address', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.box-address-billing > .box-actions > .action > span').click()
    cy.get('.base').should('contain.text', 'Edit Address')
    cy.get('#country').select('United States')
    cy.get('#company').clear()
    cy.get('#company').type('Fantasy')
    cy.get('#telephone').clear()
    cy.get('#telephone').type('+169456234521')
    cy.get('#street_1').clear()
    cy.get('#street_1').type('Rodeo Drive')
    cy.get('#city').clear()
    cy.get('#city').type('San Jose')
    cy.get('#region_id').select('California')
    cy.get('#zip').clear()
    cy.get('#zip').type('90001')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.message-success').should('contain.text', 'You saved the address.')
  })

  it('Edit Address - Change Billing Address - Failed - Delete Some Field', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.box-address-billing > .box-actions > .action > span').click()
    cy.get('.base').should('contain.text', 'Edit Address')
    cy.get('#country').select('United States')
    cy.get('#company').clear()
    cy.get('#telephone').clear()
    cy.get('#street_1').clear()
    cy.get('#city').clear()
    cy.get('#region_id').select('California')
    cy.get('#zip').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#telephone-error').should('contain.text', 'This is a required field.')
    cy.get('#street_1-error').should('contain.text', 'This is a required field.')
    cy.get('#city-error').should('contain.text', 'This is a required field.')
  })

  it('Edit Address - Change Shipping Address - Success - Change All Field on Shipping Address', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.box-address-shipping > .box-actions > .action > span').click()
    cy.get('.base').should('contain.text', 'Edit Address')
    cy.get('#country').select('Indonesia')
    cy.get('#company').clear()
    cy.get('#company').type('Jaya Abadi')
    cy.get('#telephone').clear()
    cy.get('#telephone').type('085342128564')
    cy.get('#street_1').clear()
    cy.get('#street_1').type('Jalan Jaya')
    cy.get('#city').clear()
    cy.get('#city').type('Surabaya')
    cy.get('#region').type('Jawa Timur')
    cy.get('#zip').clear()
    cy.get('#zip').type('60182')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.message-success').should('contain.text', 'You saved the address.')
  })

  it('Edit Address - Change Shipping Address - Failed - Delete Some Field', () => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > .authorization-link > a').click()
    cy.get('[data-ui-id="page-title-wrapper"]').should('contain.text', 'Customer Login')
    cy.get('#email').type('budiadmin@gmail.com')
    cy.get('#pass').type('budi12345.,')
    cy.get('#send2').click()
    cy.get('.base').should('contain.text', 'Home Page')
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.base').should('contain.text', 'My Account')
    cy.get('.box-content > p').should('contain.text', 'budi pratama')
    cy.get('.items > :nth-child(6) > a').click()
    cy.get('.base').should('contain.text', 'Address Book')
    cy.get('.box-address-shipping > .box-actions > .action > span').click()
    cy.get('.base').should('contain.text', 'Edit Address')
    cy.get('#country').select('Indonesia')
    cy.get('#company').clear()
    cy.get('#telephone').clear()
    cy.get('#street_1').clear()
    cy.get('#city').clear()
    cy.get('#region').clear()
    cy.get('#zip').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
    cy.get('#telephone-error').should('contain.text', 'This is a required field.')
    cy.get('#street_1-error').should('contain.text', 'This is a required field.')
    cy.get('#city-error').should('contain.text', 'This is a required field.')
  })
})